name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule: 
    - cron: 30 07 * * *   # 7:30 AM UTC time
    - cron: 00 16 * * *   #runs at 4 PM UTC time every day
    - cron: 00 12 * * 1-4   #runs at 12 PM UTC time Mon- Fri

  jobs:
    run-postman-tests:     #Name of the Job
      runs-on: ubuntu-latest #VM

      steps:
        - name: Checkout the code
          uses: actions/checkout@v5.0.0

        - name: Install nodejs and npm
          uses: actions/setup-node@v5.0.0
          with:
            node-version: '22'

        - name: Install newman and Html-extra
          run: |         # We use '|' for multi line cmds OR we could use "npm install -g newman && npm install -g newman-reporter-htmlextra"
               npm install -g newman
               npm install -g newman-reporter-htmlextra

        - name: Run the postman collection with Newman
          run: |
               newman run 'Inwarranty-flow Collection Copy.postman_collection.json' \
               -e QA.postman_environment.json \
               -d testdata.csv \
               -r cli,htmlextra

        






          
