name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule: 
    - cron: 30 07 * * 1   # 7:30 AM UTC time
#    - cron: 00 16 * * *   #runs at 4 PM UTC time every day
#    - cron: 00 12 * * 1-4   #runs at 12 PM UTC time Mon- Fri

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest #VM

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0

      - name: Install nodejs and npm
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '22'

      - name: Install newman and Html-extra
        run: |         # We use '|' for multi line cmds OR we could use "npm install -g newman && npm install -g newman-reporter-htmlextra"
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the postman collection with Newman
        run: |
             newman run 'Inwarranty-flow Collection Copy.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testdata.csv \
             -r cli,htmlextra \
             --reporter-htmlextra-export ./newman/index.html

      - name: Newman report
        if: always() #ensure archive is executed even if your tests fail
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Newman report
          path: newman/*.html

      - name: Creating github page branch  #Github Pages Action by peaceiris
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name: Send Email Notifications
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Postman API Tests
          to: vickygc2001@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
                Hi,
                Postman Automation reports attached
                Link : https://vickygc2001.github.io/Postman-Collections-Inwarranty/
          



          
